### ISSUE TITLE
The aiengine cann't directly parse packet  of pcap file?

### ISSUE THREAD

**Issue by yashengsun** [camp0/aiengine#1]
I want to parse a pcap file by aiengine, but I only can gain flows of the pcap.
Question:
     how to gain each packet of the pcap file? I want to traversing each packet.

**Comment by camp0** [comment]
You can create a regex that match everything, but this will only shows packets with application layer payload.

./aiengine -i <pcapfile> p -R -r "^.*$" -m -M

**Comment by yashengsun** [comment]
thanks a lot.
I already gain every packet's payload from each flow, but it hasn't timestamp value.
why?

**Comment by camp0** [comment]
Because I didn't consider interesting show the timestamp, if you think that is important you can submit the changes via pull request :)
