### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by lovebingheji** [camp0/aiengine#2]
I use python， sometimes the program print the error: 

re = pyaiengine.Regex(domain, domain)\n', 'RuntimeError: unidentifiable C++ exception\n'], u'type': "<type 'exceptions.RuntimeError'>", u'value': 'unidentifiable C++ exception'

what is this mean? and how should i do ?

**Comment by camp0** [comment]
looks that the regular expression is not correct, would you mind to post more code to see exactly what are you doing? specially the content of the variable domain.
